#!/bin/sh
#/etc/init.d/tv_remote

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules:/home/pi/node-tv-remote

case "$1" in
  start)
  exec forever start --sourceDir=/home/pi/node-tv-remote -a -l  /root/forever.log -o  /root/out.log -e /root/err.log server.js
  ;;
stop)
  exec forever --sourceDir=/home/pi/node-tv-remote stop server.js
  ;;
*)
  echo "Usage: /etc/init.d/tv_remote {start|stop}"
  exit 1
  ;;
esac

exit 0
